openapi: 3.0.0
info:
  title: Sumagro-2.0
  version: 1.0.0
paths:
 /sumagro-app/register:
   post:
    tags:
      - ADMIN
    summary: "Service designed to send registration message to Email"
    operationId: "register"
    parameters:
      - in: header
        required: true
        name: token
        schema:
          type: "string"
          format: uuid
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/userRegisterRequest"
    responses:
      204:
        description: "Register Successfull"
        
 /sumagro-app/order:
  post:
    tags:
      - ADMIN
    summary: "Service designed to save a order by user"
    operationId: "registerOrder"
    parameters:
      - in: header
        required: true
        name: token
        schema:
          type: "string"
          format: uuid
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/orderRequest"
    responses:
      204:
        description: "Register Successfull"
  get:
    tags:
      - ADMIN
    summary: "service designed to list of orders"
    operationId: "listOrders"
    parameters:
      - in: header
        required: true
        name: token
        schema:
          type: "string"
          format: uuid
    responses:
      200:
        description: "orders"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/listOrders"
 /sumagro-app/order/{orderId}:
  patch:
    tags:
      - CAPTURIST
    summary: "service designed to update status of order"
    operationId: "orderStatus"
    parameters:
      - in: header
        required: true
        name: token
        schema:
          type: "string"
          format: uuid
      - in: path
        required: true
        name: orderId
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/orderStatusUpdate"
    responses:
      200:
        description: "ordersUpdateStatus"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Success"
 /sumagro-app/token:
  post:
    tags:
      - DEFAULT
    summary: "service designed to assing token a user"
    operationId: "generateToken"
    parameters:
      - in: header
        required: true
        name: token
        schema:
          type: "string"
          format: uuid
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/tokenBody"
    responses:
      201:
        description: "Token Registered"
  delete:
    tags:
      - DEFAULT
    summary: "service designed to delete a token of a user"
    operationId: "deleteToken"
    parameters:
      - in: header
        required: true
        name: token
        schema:
          type: "string"
          format: uuid
    responses:
      201:
        description: "Token Erased"
 '/sumagro-app/generate-pdf/:orderId':
  get:
    tags:
      - ADMIN
    summary: "Method designed to get a PDF of an Order"
    operationId: "GeneratePDF"
    parameters:
      - in: header
        required: true
        name: token
        schema:
          type: "string"
          format: uuid
      - in: path
        required: true
        name: orderId
        schema:
          type: "string"
          format: "uuid"
    responses:
      200: 
        description: "PDF"
 /sumagro-app/generate-pdf/chargeformat:
   get:
    tags:
      - ADMIN
    summary: "method designed to generate a pdf by orderId"
    operationId: "generatePdfByOrder"
    parameters:
      - in: header
        required: true
        name: token
        schema:
          type: "string"
          format: uuid
    responses:
      200:
        description: "PDF"
 /sumagro-app/send-pdf/:orderId:
   post:
    tags:
      - ADMIN
    summary: "method designed to send a email with pdf by orderId"
    operationId: "senderPdf"
    parameters:
      - in: header
        required: true
        name: token
        schema:
          type: "string"
          format: uuid
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/pdfSenderRequest"
    responses:
      200: 
        description: "Sended"
components:
  schemas:
    pdfSenderRequest:
      type: object
      properties:
        email:
          type: string
    tokenBody:
      type: object
      properties:
        token:
          type: string
    Success:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    userRegisterRequest:
      type: object
      properties:
        email:
          type: "string"
        password:
          type: "string"
    orderRequest:
      type: object
      properties:
        enterpriseName:
          type: string
        RFC:
          type: string
        address:
          type: string
        client:
          type: string
        clientAddress:
          type: string
        remissionNumber:
          type: number
        shippingDate:
          type: string
          format: date
        subOrders:
          type: array
          items:
            type: object
            properties:
              quantity:
                type: number
              unit:
                type: string
              description:
                type: string
              unitPrice:
                type: number
              total:
                type: number
        totalGeneral:
          type: number
        advance:
          type: number
    listOrders:
      type: array
      items:
        type: object
        properties:
          orderId:
            type: number
          enterpriseName:
            type: string
          RFC:
            type: string
          address:
            type: string
          client:
            type: string
          clientAddress:
            type: string
          remissionNumber:
            type: number
          shippingDate:
            type: string
            format: date
          subOrders:
            type: array
            items:
              type: object
              properties:
                quantity:
                  type: number
                unit:
                  type: string
                description:
                  type: string
                unitPrice:
                  type: number
                total:
                  type: number
          totalGeneral:
            type: number
          advance:
            type: number
          status:
            type: string
    orderStatusUpdate:
      type: object
      properties:
        status:
          type: "string"
          enum:
            - TRANSIT
            - DELIVERED
            - ORDER_CLOSED
          
      
  
   